export const FETCH_CARDS = 'FETCH_CARDS';
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARDS_FAILED = 'FETCH_CARDS_FAILED';

export const LOAD_CARD = 'LOAD_CARD';
export const UPLOAD_CARD = 'UPLOAD_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const FILTER_CARDS = 'FILTER_CARDS';